version: '3'

services:
  api:
    build:
      context: ./api
    volumes:
      - ./api:/app
    depends_on:
      - db

  server:
    build:
      context: ./server
    volumes:
      - ./server:/app
      - node_modules_server:/app/node_modules
    depends_on:
      - db

  web:
    build:
      context: ./web
    volumes:
      - ./web:/app
      - node_modules_web:/app/node_modules
    depends_on:
#      - api
      - server

  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: USER
      POSTGRES_PASSWORD: PASSWORD

  nginx:
    image: media_poc_nginx
    build:
      context: ./nginx
    environment:
      PROXY_TARGET: "web:3000"
      API_PROXY_TARGET: "api:8000"
    depends_on:
      - api
      - web

volumes:
  db: { }
  node_modules_web: { }
  node_modules_server: { }